### ISSUE TITLE
hi ，i have a problem

### ISSUE THREAD

**Issue by bjlizelin** [macacajs/reliable#72]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/38234865/61861523-b0a46200-aefe-11e9-8859-0aab5b2749ca.png">

**Comment by zhechengmao** [comment]
运行该命令前，需要把docker的服务先起来
命令如下：
docker-compose -p reliable -f docker-compose.yml up -d

**Comment by bjlizelin** [comment]
> 运行该命令前，需要把docker的服务先起来
> 命令如下：
> docker-compose -p reliable -f docker-compose.yml up -d

大哥，我现在是这么处理的，我是直接从mysql数据库把jobname 改成jobName 但是去执行docker-compose up 仍是会提示找不到数据库Table 'reliable.SequelizeMeta' doesn't exist，是不是我需要先去执行下这个https://github.com/macacajs/reliable/blob/master/docker/reliable-mysql/README.md ？大哥求求你详细讲讲吧

**Comment by zhechengmao** [comment]
> > 运行该命令前，需要把docker的服务先起来
> > 命令如下：
> > docker-compose -p reliable -f docker-compose.yml up -d
> 
> 大哥，我现在是这么处理的，我是直接从mysql数据库把jobname 改成jobName 但是去执行docker-compose up 仍是会提示找不到数据库Table 'reliable.SequelizeMeta' doesn't exist，是不是我需要先去执行下这个https://github.com/macacajs/reliable/blob/master/docker/reliable-mysql/README.md ？大哥求求你详细讲讲吧

我是按照这个教程来的，一步一步操作下来的，至于你说的这个mysql数据库改东西，我还没涉及。你用docker ps命令，看一下你的服务都起来了没，教程如下：
https://testerhome.com/topics/19743

![image](https://user-images.githubusercontent.com/13476451/61865892-ad14d900-af06-11e9-8e81-0a184077debc.png)

**Comment by bjlizelin** [comment]
> https://testerhome.com/topics/19743
明白了，我明天重新部署下，大哥能方便加你qq或者邮箱吗？macaca 我从ios真机到这里真的搞得头大

**Comment by zhechengmao** [comment]
> > https://testerhome.com/topics/19743
> > 明白了，我明天重新部署下，大哥能方便加你qq或者邮箱吗？macaca 我从ios真机到这里真的搞得头大

钉钉群号：11775486，你可以进这个群，我也在这个群里，大家一起学习。

**Comment by bjlizelin** [comment]
> 11775486

ok，万分感激！！
