### ISSUE TITLE
关于reliable 的sample 测试报告

### ISSUE THREAD

**Issue by Arvingrep** [macacajs/reliable#74]
1、缺少 测试结果跳转
![image](https://user-images.githubusercontent.com/48466044/68363864-2f987000-0167-11ea-9bfb-130228199230.png)
2、 构建产物 已经copy保存完成都是没有没办法正常跳转
![image](https://user-images.githubusercontent.com/48466044/68364140-117f3f80-0168-11ea-8e5a-85d86bfb2a0e.png)

**Comment by wenzhaoxian** [comment]
这个reliable中展现的bug，负责人能抽空帮忙一下吗，这个bug影响到核心功能： 集成的报告展示

**Comment by Arvingrep** [comment]
这个核心功能的bug，谁可以花时间精力处理一下吗，我基础差，而且前端技术一直都吃的急。 真心希望好心人有偿处理（可以直接联系我），等了快一年了

**Comment by Arvingrep** [comment]
> 这个reliable中展现的bug，负责人能抽空帮忙一下吗，这个bug影响到核心功能： 集成的报告展示

**Comment by yihuineng** [comment]
请研究下 http://npmjs.com/reliable-cli 的原理
